/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compi1_exregan;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author danis
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vistra
     */
    
    JFileChooser dialog = new JFileChooser();
    File rutas_ar;
    FileInputStream entrada;
    FileOutputStream salida;
    File archivo;
    
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtarea1 = new javax.swing.JTextArea();
        area2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_nuevo = new javax.swing.JMenuItem();
        jm_abrir = new javax.swing.JMenuItem();
        jm_guardar = new javax.swing.JMenuItem();
        jm_guardarc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtarea1.setColumns(20);
        jtxtarea1.setRows(5);
        jScrollPane1.setViewportView(jtxtarea1);

        area2.setColumns(20);
        area2.setRows(5);

        jMenu1.setText("Archivo");

        jm_nuevo.setText("Nuevo");
        jm_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_nuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jm_nuevo);

        jm_abrir.setText("Abrir");
        jm_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_abrirActionPerformed(evt);
            }
        });
        jMenu1.add(jm_abrir);

        jm_guardar.setText("Guardar");
        jm_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardarActionPerformed(evt);
            }
        });
        jMenu1.add(jm_guardar);

        jm_guardarc.setText("Guardar como...");
        jm_guardarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardarcActionPerformed(evt);
            }
        });
        jMenu1.add(jm_guardarc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_nuevoActionPerformed
        // TODO add your handling code here:
        jtxtarea1.setText("");
    }//GEN-LAST:event_jm_nuevoActionPerformed

    private void jm_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardarActionPerformed
        // TODO add your handling code here:
        if (rutas_ar == null)
        {
            JOptionPane.showMessageDialog(null, "No hay ningun archivo");
        }
        else
        {
            ////            JOptionPane.showMessageDialog(null, rutas_ar);

            //        if(dialog.showDialog(null, "Guardar Arhivo") == JFileChooser.APPROVE_OPTION )
            //        {
                String ruta;
                //archivo = dialog.getSelectedFile();
                archivo = rutas_ar;

                ruta = archivo.toString();
                //ruta = ruta + ".dat";
                archivo = new File(ruta);
                //            JOptionPane.showMessageDialog(null, archivo);

                GuardarAhora(archivo);
        }
    }//GEN-LAST:event_jm_guardarActionPerformed

    private void jm_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_abrirActionPerformed
        // TODO add your handling code here:
        if(dialog.showDialog(null, "Abrir docuemnto")== JFileChooser.APPROVE_OPTION)
        {
            boolean ya = false;
            archivo = dialog.getSelectedFile();
            if(archivo.canRead() )
            {
                ////                JOptionPane.showMessageDialog(null, "archivo: " + archivo);
                /*verificando si ya tiene abierto el arhicvo*/
                    if (archivo.equals(rutas_ar))
                    {
                        JOptionPane.showMessageDialog(null,  "El documento " + archivo.getName() + " ya esta abierto" );
                        ya = true;
                    }
                    //                }
                /*fin*/
                if(ya == false){

                    if(archivo.getName().endsWith("olc") )
                    {
                        //JOptionPane.showMessageDialog(null,  archivo.getName() );
                        String contenido = AbrirArhivo(archivo);
                        jtxtarea1.setText(contenido);
                        rutas_ar = archivo;
                        this.setTitle(archivo.getName());
                        //                    InsertaPesta(contenido, archivo.getName());
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Extencion incorrecta");
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No puede abrir archivo");
            }
        }
    }//GEN-LAST:event_jm_abrirActionPerformed

    private void jm_guardarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardarcActionPerformed
        // TODO add your handling code here:
        if(dialog.showDialog(null, "Guardar Arhivo") == JFileChooser.APPROVE_OPTION )
        {
            String ruta;
            archivo = dialog.getSelectedFile();
            ruta = archivo.toString();
            ruta = ruta + ".olc";
            archivo = new File(ruta);
            //JOptionPane.showMessageDialog(null, archivo);
            
            GuardarAhora(archivo);
            
            rutas_ar = archivo;
            this.setTitle(archivo.getName());
        }
    }//GEN-LAST:event_jm_guardarcActionPerformed

    public String AbrirArhivo(File archivo)
    {
        String document = "";
        try {
            String cadena;
            FileReader f = new FileReader(archivo);
            BufferedReader b = new BufferedReader(f);
            while((cadena = b.readLine())!=null) {
                //System.out.println(cadena);
                document = document + cadena + '\n';
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        return document;
    }
    
    public void GuardarAhora(File archivo_g)
    {
        //if (archivo_g.getName().endsWith("dat"))
          //  {
                String doc = jtxtarea1.getText();
                //JOptionPane.showMessageDialog(null, doc);      
                
                boolean pasa = GuardarArchivo(archivo_g, doc);
                
                if (pasa == false)                
                {
                    JOptionPane.showMessageDialog(null, "error al guardar achivo");
                }
                JOptionPane.showMessageDialog(null, "archivo guardado");
            //}
        
    }
    
    public boolean GuardarArchivo(File arhivo, String documento)
    {
        boolean pasa = true;
        try {
            salida = new FileOutputStream(arhivo);
            byte[] bytxt = documento.getBytes();
            salida.write(bytxt);
            //arhivo_actual = arhivo;
            
        } catch (Exception e) {
            pasa = false;
        }
         return pasa;   
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jm_abrir;
    private javax.swing.JMenuItem jm_guardar;
    private javax.swing.JMenuItem jm_guardarc;
    private javax.swing.JMenuItem jm_nuevo;
    private javax.swing.JTextArea jtxtarea1;
    // End of variables declaration//GEN-END:variables
}
